# Generated by Django 2.0.5 on 2018-05-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
