# Generated by Django 2.0.5 on 2018-05-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
        ('catalog', '0003_productvariant_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='params.Vendor'),
        ),
    ]
