# Generated by Django 2.0.5 on 2018-05-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
    ]
